// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BBHierarchyTreeWidgetItem.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_BBHierarchyTreeWidgetItem_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_BBHierarchyTreeWidgetItem_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3016000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3016000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_BBHierarchyTreeWidgetItem_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_BBHierarchyTreeWidgetItem_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BBHierarchyTreeWidgetItem_2eproto;
namespace BBSerializer {
class BBHierarchyTreeWidgetItem;
struct BBHierarchyTreeWidgetItemDefaultTypeInternal;
extern BBHierarchyTreeWidgetItemDefaultTypeInternal _BBHierarchyTreeWidgetItem_default_instance_;
}  // namespace BBSerializer
PROTOBUF_NAMESPACE_OPEN
template<> ::BBSerializer::BBHierarchyTreeWidgetItem* Arena::CreateMaybeMessage<::BBSerializer::BBHierarchyTreeWidgetItem>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace BBSerializer {

// ===================================================================

class BBHierarchyTreeWidgetItem PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:BBSerializer.BBHierarchyTreeWidgetItem) */ {
 public:
  inline BBHierarchyTreeWidgetItem() : BBHierarchyTreeWidgetItem(nullptr) {}
  ~BBHierarchyTreeWidgetItem() override;
  explicit constexpr BBHierarchyTreeWidgetItem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BBHierarchyTreeWidgetItem(const BBHierarchyTreeWidgetItem& from);
  BBHierarchyTreeWidgetItem(BBHierarchyTreeWidgetItem&& from) noexcept
    : BBHierarchyTreeWidgetItem() {
    *this = ::std::move(from);
  }

  inline BBHierarchyTreeWidgetItem& operator=(const BBHierarchyTreeWidgetItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline BBHierarchyTreeWidgetItem& operator=(BBHierarchyTreeWidgetItem&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BBHierarchyTreeWidgetItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const BBHierarchyTreeWidgetItem* internal_default_instance() {
    return reinterpret_cast<const BBHierarchyTreeWidgetItem*>(
               &_BBHierarchyTreeWidgetItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BBHierarchyTreeWidgetItem& a, BBHierarchyTreeWidgetItem& b) {
    a.Swap(&b);
  }
  inline void Swap(BBHierarchyTreeWidgetItem* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BBHierarchyTreeWidgetItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BBHierarchyTreeWidgetItem* New() const final {
    return CreateMaybeMessage<BBHierarchyTreeWidgetItem>(nullptr);
  }

  BBHierarchyTreeWidgetItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BBHierarchyTreeWidgetItem>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BBHierarchyTreeWidgetItem& from);
  void MergeFrom(const BBHierarchyTreeWidgetItem& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BBHierarchyTreeWidgetItem* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "BBSerializer.BBHierarchyTreeWidgetItem";
  }
  protected:
  explicit BBHierarchyTreeWidgetItem(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParentIndexFieldNumber = 1,
  };
  // int32 parentIndex = 1;
  bool has_parentindex() const;
  private:
  bool _internal_has_parentindex() const;
  public:
  void clear_parentindex();
  ::PROTOBUF_NAMESPACE_ID::int32 parentindex() const;
  void set_parentindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_parentindex() const;
  void _internal_set_parentindex(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:BBSerializer.BBHierarchyTreeWidgetItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 parentindex_;
  friend struct ::TableStruct_BBHierarchyTreeWidgetItem_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BBHierarchyTreeWidgetItem

// int32 parentIndex = 1;
inline bool BBHierarchyTreeWidgetItem::_internal_has_parentindex() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool BBHierarchyTreeWidgetItem::has_parentindex() const {
  return _internal_has_parentindex();
}
inline void BBHierarchyTreeWidgetItem::clear_parentindex() {
  parentindex_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BBHierarchyTreeWidgetItem::_internal_parentindex() const {
  return parentindex_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 BBHierarchyTreeWidgetItem::parentindex() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBHierarchyTreeWidgetItem.parentIndex)
  return _internal_parentindex();
}
inline void BBHierarchyTreeWidgetItem::_internal_set_parentindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  parentindex_ = value;
}
inline void BBHierarchyTreeWidgetItem::set_parentindex(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_parentindex(value);
  // @@protoc_insertion_point(field_set:BBSerializer.BBHierarchyTreeWidgetItem.parentIndex)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace BBSerializer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_BBHierarchyTreeWidgetItem_2eproto
