// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BBMaterial.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_BBMaterial_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_BBMaterial_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3016000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3016000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "BBVector.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_BBMaterial_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_BBMaterial_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BBMaterial_2eproto;
namespace BBSerializer {
class BBMaterial;
struct BBMaterialDefaultTypeInternal;
extern BBMaterialDefaultTypeInternal _BBMaterial_default_instance_;
}  // namespace BBSerializer
PROTOBUF_NAMESPACE_OPEN
template<> ::BBSerializer::BBMaterial* Arena::CreateMaybeMessage<::BBSerializer::BBMaterial>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace BBSerializer {

// ===================================================================

class BBMaterial PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:BBSerializer.BBMaterial) */ {
 public:
  inline BBMaterial() : BBMaterial(nullptr) {}
  ~BBMaterial() override;
  explicit constexpr BBMaterial(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BBMaterial(const BBMaterial& from);
  BBMaterial(BBMaterial&& from) noexcept
    : BBMaterial() {
    *this = ::std::move(from);
  }

  inline BBMaterial& operator=(const BBMaterial& from) {
    CopyFrom(from);
    return *this;
  }
  inline BBMaterial& operator=(BBMaterial&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BBMaterial& default_instance() {
    return *internal_default_instance();
  }
  static inline const BBMaterial* internal_default_instance() {
    return reinterpret_cast<const BBMaterial*>(
               &_BBMaterial_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BBMaterial& a, BBMaterial& b) {
    a.Swap(&b);
  }
  inline void Swap(BBMaterial* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BBMaterial* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BBMaterial* New() const final {
    return CreateMaybeMessage<BBMaterial>(nullptr);
  }

  BBMaterial* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BBMaterial>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BBMaterial& from);
  void MergeFrom(const BBMaterial& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BBMaterial* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "BBSerializer.BBMaterial";
  }
  protected:
  explicit BBMaterial(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShaderNameFieldNumber = 1,
    kVShaderPathFieldNumber = 2,
    kFShaderPathFieldNumber = 3,
    kTexture0PathFieldNumber = 4,
    kTexture1PathFieldNumber = 5,
    kTexture2PathFieldNumber = 6,
    kTexture3PathFieldNumber = 7,
    kTexture4PathFieldNumber = 8,
    kTexture5PathFieldNumber = 9,
    kTexture6PathFieldNumber = 10,
    kTexture7PathFieldNumber = 11,
  };
  // string shaderName = 1;
  bool has_shadername() const;
  private:
  bool _internal_has_shadername() const;
  public:
  void clear_shadername();
  const std::string& shadername() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_shadername(ArgT0&& arg0, ArgT... args);
  std::string* mutable_shadername();
  std::string* release_shadername();
  void set_allocated_shadername(std::string* shadername);
  private:
  const std::string& _internal_shadername() const;
  void _internal_set_shadername(const std::string& value);
  std::string* _internal_mutable_shadername();
  public:

  // string vShaderPath = 2;
  bool has_vshaderpath() const;
  private:
  bool _internal_has_vshaderpath() const;
  public:
  void clear_vshaderpath();
  const std::string& vshaderpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_vshaderpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_vshaderpath();
  std::string* release_vshaderpath();
  void set_allocated_vshaderpath(std::string* vshaderpath);
  private:
  const std::string& _internal_vshaderpath() const;
  void _internal_set_vshaderpath(const std::string& value);
  std::string* _internal_mutable_vshaderpath();
  public:

  // string fShaderPath = 3;
  bool has_fshaderpath() const;
  private:
  bool _internal_has_fshaderpath() const;
  public:
  void clear_fshaderpath();
  const std::string& fshaderpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_fshaderpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_fshaderpath();
  std::string* release_fshaderpath();
  void set_allocated_fshaderpath(std::string* fshaderpath);
  private:
  const std::string& _internal_fshaderpath() const;
  void _internal_set_fshaderpath(const std::string& value);
  std::string* _internal_mutable_fshaderpath();
  public:

  // string texture0Path = 4;
  bool has_texture0path() const;
  private:
  bool _internal_has_texture0path() const;
  public:
  void clear_texture0path();
  const std::string& texture0path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_texture0path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_texture0path();
  std::string* release_texture0path();
  void set_allocated_texture0path(std::string* texture0path);
  private:
  const std::string& _internal_texture0path() const;
  void _internal_set_texture0path(const std::string& value);
  std::string* _internal_mutable_texture0path();
  public:

  // string texture1Path = 5;
  bool has_texture1path() const;
  private:
  bool _internal_has_texture1path() const;
  public:
  void clear_texture1path();
  const std::string& texture1path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_texture1path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_texture1path();
  std::string* release_texture1path();
  void set_allocated_texture1path(std::string* texture1path);
  private:
  const std::string& _internal_texture1path() const;
  void _internal_set_texture1path(const std::string& value);
  std::string* _internal_mutable_texture1path();
  public:

  // string texture2Path = 6;
  bool has_texture2path() const;
  private:
  bool _internal_has_texture2path() const;
  public:
  void clear_texture2path();
  const std::string& texture2path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_texture2path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_texture2path();
  std::string* release_texture2path();
  void set_allocated_texture2path(std::string* texture2path);
  private:
  const std::string& _internal_texture2path() const;
  void _internal_set_texture2path(const std::string& value);
  std::string* _internal_mutable_texture2path();
  public:

  // string texture3Path = 7;
  bool has_texture3path() const;
  private:
  bool _internal_has_texture3path() const;
  public:
  void clear_texture3path();
  const std::string& texture3path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_texture3path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_texture3path();
  std::string* release_texture3path();
  void set_allocated_texture3path(std::string* texture3path);
  private:
  const std::string& _internal_texture3path() const;
  void _internal_set_texture3path(const std::string& value);
  std::string* _internal_mutable_texture3path();
  public:

  // string texture4Path = 8;
  bool has_texture4path() const;
  private:
  bool _internal_has_texture4path() const;
  public:
  void clear_texture4path();
  const std::string& texture4path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_texture4path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_texture4path();
  std::string* release_texture4path();
  void set_allocated_texture4path(std::string* texture4path);
  private:
  const std::string& _internal_texture4path() const;
  void _internal_set_texture4path(const std::string& value);
  std::string* _internal_mutable_texture4path();
  public:

  // string texture5Path = 9;
  bool has_texture5path() const;
  private:
  bool _internal_has_texture5path() const;
  public:
  void clear_texture5path();
  const std::string& texture5path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_texture5path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_texture5path();
  std::string* release_texture5path();
  void set_allocated_texture5path(std::string* texture5path);
  private:
  const std::string& _internal_texture5path() const;
  void _internal_set_texture5path(const std::string& value);
  std::string* _internal_mutable_texture5path();
  public:

  // string texture6Path = 10;
  bool has_texture6path() const;
  private:
  bool _internal_has_texture6path() const;
  public:
  void clear_texture6path();
  const std::string& texture6path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_texture6path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_texture6path();
  std::string* release_texture6path();
  void set_allocated_texture6path(std::string* texture6path);
  private:
  const std::string& _internal_texture6path() const;
  void _internal_set_texture6path(const std::string& value);
  std::string* _internal_mutable_texture6path();
  public:

  // string texture7Path = 11;
  bool has_texture7path() const;
  private:
  bool _internal_has_texture7path() const;
  public:
  void clear_texture7path();
  const std::string& texture7path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_texture7path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_texture7path();
  std::string* release_texture7path();
  void set_allocated_texture7path(std::string* texture7path);
  private:
  const std::string& _internal_texture7path() const;
  void _internal_set_texture7path(const std::string& value);
  std::string* _internal_mutable_texture7path();
  public:

  // @@protoc_insertion_point(class_scope:BBSerializer.BBMaterial)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr shadername_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr vshaderpath_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fshaderpath_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr texture0path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr texture1path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr texture2path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr texture3path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr texture4path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr texture5path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr texture6path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr texture7path_;
  friend struct ::TableStruct_BBMaterial_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BBMaterial

// string shaderName = 1;
inline bool BBMaterial::_internal_has_shadername() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool BBMaterial::has_shadername() const {
  return _internal_has_shadername();
}
inline void BBMaterial::clear_shadername() {
  shadername_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& BBMaterial::shadername() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBMaterial.shaderName)
  return _internal_shadername();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void BBMaterial::set_shadername(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 shadername_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:BBSerializer.BBMaterial.shaderName)
}
inline std::string* BBMaterial::mutable_shadername() {
  // @@protoc_insertion_point(field_mutable:BBSerializer.BBMaterial.shaderName)
  return _internal_mutable_shadername();
}
inline const std::string& BBMaterial::_internal_shadername() const {
  return shadername_.Get();
}
inline void BBMaterial::_internal_set_shadername(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  shadername_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* BBMaterial::_internal_mutable_shadername() {
  _has_bits_[0] |= 0x00000001u;
  return shadername_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BBMaterial::release_shadername() {
  // @@protoc_insertion_point(field_release:BBSerializer.BBMaterial.shaderName)
  if (!_internal_has_shadername()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return shadername_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BBMaterial::set_allocated_shadername(std::string* shadername) {
  if (shadername != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  shadername_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), shadername,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BBSerializer.BBMaterial.shaderName)
}

// string vShaderPath = 2;
inline bool BBMaterial::_internal_has_vshaderpath() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool BBMaterial::has_vshaderpath() const {
  return _internal_has_vshaderpath();
}
inline void BBMaterial::clear_vshaderpath() {
  vshaderpath_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& BBMaterial::vshaderpath() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBMaterial.vShaderPath)
  return _internal_vshaderpath();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void BBMaterial::set_vshaderpath(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 vshaderpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:BBSerializer.BBMaterial.vShaderPath)
}
inline std::string* BBMaterial::mutable_vshaderpath() {
  // @@protoc_insertion_point(field_mutable:BBSerializer.BBMaterial.vShaderPath)
  return _internal_mutable_vshaderpath();
}
inline const std::string& BBMaterial::_internal_vshaderpath() const {
  return vshaderpath_.Get();
}
inline void BBMaterial::_internal_set_vshaderpath(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  vshaderpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* BBMaterial::_internal_mutable_vshaderpath() {
  _has_bits_[0] |= 0x00000002u;
  return vshaderpath_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BBMaterial::release_vshaderpath() {
  // @@protoc_insertion_point(field_release:BBSerializer.BBMaterial.vShaderPath)
  if (!_internal_has_vshaderpath()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return vshaderpath_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BBMaterial::set_allocated_vshaderpath(std::string* vshaderpath) {
  if (vshaderpath != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  vshaderpath_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), vshaderpath,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BBSerializer.BBMaterial.vShaderPath)
}

// string fShaderPath = 3;
inline bool BBMaterial::_internal_has_fshaderpath() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool BBMaterial::has_fshaderpath() const {
  return _internal_has_fshaderpath();
}
inline void BBMaterial::clear_fshaderpath() {
  fshaderpath_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& BBMaterial::fshaderpath() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBMaterial.fShaderPath)
  return _internal_fshaderpath();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void BBMaterial::set_fshaderpath(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 fshaderpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:BBSerializer.BBMaterial.fShaderPath)
}
inline std::string* BBMaterial::mutable_fshaderpath() {
  // @@protoc_insertion_point(field_mutable:BBSerializer.BBMaterial.fShaderPath)
  return _internal_mutable_fshaderpath();
}
inline const std::string& BBMaterial::_internal_fshaderpath() const {
  return fshaderpath_.Get();
}
inline void BBMaterial::_internal_set_fshaderpath(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  fshaderpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* BBMaterial::_internal_mutable_fshaderpath() {
  _has_bits_[0] |= 0x00000004u;
  return fshaderpath_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BBMaterial::release_fshaderpath() {
  // @@protoc_insertion_point(field_release:BBSerializer.BBMaterial.fShaderPath)
  if (!_internal_has_fshaderpath()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return fshaderpath_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BBMaterial::set_allocated_fshaderpath(std::string* fshaderpath) {
  if (fshaderpath != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  fshaderpath_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fshaderpath,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BBSerializer.BBMaterial.fShaderPath)
}

// string texture0Path = 4;
inline bool BBMaterial::_internal_has_texture0path() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool BBMaterial::has_texture0path() const {
  return _internal_has_texture0path();
}
inline void BBMaterial::clear_texture0path() {
  texture0path_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& BBMaterial::texture0path() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBMaterial.texture0Path)
  return _internal_texture0path();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void BBMaterial::set_texture0path(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000008u;
 texture0path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:BBSerializer.BBMaterial.texture0Path)
}
inline std::string* BBMaterial::mutable_texture0path() {
  // @@protoc_insertion_point(field_mutable:BBSerializer.BBMaterial.texture0Path)
  return _internal_mutable_texture0path();
}
inline const std::string& BBMaterial::_internal_texture0path() const {
  return texture0path_.Get();
}
inline void BBMaterial::_internal_set_texture0path(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  texture0path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* BBMaterial::_internal_mutable_texture0path() {
  _has_bits_[0] |= 0x00000008u;
  return texture0path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BBMaterial::release_texture0path() {
  // @@protoc_insertion_point(field_release:BBSerializer.BBMaterial.texture0Path)
  if (!_internal_has_texture0path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return texture0path_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BBMaterial::set_allocated_texture0path(std::string* texture0path) {
  if (texture0path != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  texture0path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), texture0path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BBSerializer.BBMaterial.texture0Path)
}

// string texture1Path = 5;
inline bool BBMaterial::_internal_has_texture1path() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool BBMaterial::has_texture1path() const {
  return _internal_has_texture1path();
}
inline void BBMaterial::clear_texture1path() {
  texture1path_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000010u;
}
inline const std::string& BBMaterial::texture1path() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBMaterial.texture1Path)
  return _internal_texture1path();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void BBMaterial::set_texture1path(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000010u;
 texture1path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:BBSerializer.BBMaterial.texture1Path)
}
inline std::string* BBMaterial::mutable_texture1path() {
  // @@protoc_insertion_point(field_mutable:BBSerializer.BBMaterial.texture1Path)
  return _internal_mutable_texture1path();
}
inline const std::string& BBMaterial::_internal_texture1path() const {
  return texture1path_.Get();
}
inline void BBMaterial::_internal_set_texture1path(const std::string& value) {
  _has_bits_[0] |= 0x00000010u;
  texture1path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* BBMaterial::_internal_mutable_texture1path() {
  _has_bits_[0] |= 0x00000010u;
  return texture1path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BBMaterial::release_texture1path() {
  // @@protoc_insertion_point(field_release:BBSerializer.BBMaterial.texture1Path)
  if (!_internal_has_texture1path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000010u;
  return texture1path_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BBMaterial::set_allocated_texture1path(std::string* texture1path) {
  if (texture1path != nullptr) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  texture1path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), texture1path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BBSerializer.BBMaterial.texture1Path)
}

// string texture2Path = 6;
inline bool BBMaterial::_internal_has_texture2path() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool BBMaterial::has_texture2path() const {
  return _internal_has_texture2path();
}
inline void BBMaterial::clear_texture2path() {
  texture2path_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000020u;
}
inline const std::string& BBMaterial::texture2path() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBMaterial.texture2Path)
  return _internal_texture2path();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void BBMaterial::set_texture2path(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000020u;
 texture2path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:BBSerializer.BBMaterial.texture2Path)
}
inline std::string* BBMaterial::mutable_texture2path() {
  // @@protoc_insertion_point(field_mutable:BBSerializer.BBMaterial.texture2Path)
  return _internal_mutable_texture2path();
}
inline const std::string& BBMaterial::_internal_texture2path() const {
  return texture2path_.Get();
}
inline void BBMaterial::_internal_set_texture2path(const std::string& value) {
  _has_bits_[0] |= 0x00000020u;
  texture2path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* BBMaterial::_internal_mutable_texture2path() {
  _has_bits_[0] |= 0x00000020u;
  return texture2path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BBMaterial::release_texture2path() {
  // @@protoc_insertion_point(field_release:BBSerializer.BBMaterial.texture2Path)
  if (!_internal_has_texture2path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000020u;
  return texture2path_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BBMaterial::set_allocated_texture2path(std::string* texture2path) {
  if (texture2path != nullptr) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  texture2path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), texture2path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BBSerializer.BBMaterial.texture2Path)
}

// string texture3Path = 7;
inline bool BBMaterial::_internal_has_texture3path() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool BBMaterial::has_texture3path() const {
  return _internal_has_texture3path();
}
inline void BBMaterial::clear_texture3path() {
  texture3path_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000040u;
}
inline const std::string& BBMaterial::texture3path() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBMaterial.texture3Path)
  return _internal_texture3path();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void BBMaterial::set_texture3path(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000040u;
 texture3path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:BBSerializer.BBMaterial.texture3Path)
}
inline std::string* BBMaterial::mutable_texture3path() {
  // @@protoc_insertion_point(field_mutable:BBSerializer.BBMaterial.texture3Path)
  return _internal_mutable_texture3path();
}
inline const std::string& BBMaterial::_internal_texture3path() const {
  return texture3path_.Get();
}
inline void BBMaterial::_internal_set_texture3path(const std::string& value) {
  _has_bits_[0] |= 0x00000040u;
  texture3path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* BBMaterial::_internal_mutable_texture3path() {
  _has_bits_[0] |= 0x00000040u;
  return texture3path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BBMaterial::release_texture3path() {
  // @@protoc_insertion_point(field_release:BBSerializer.BBMaterial.texture3Path)
  if (!_internal_has_texture3path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000040u;
  return texture3path_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BBMaterial::set_allocated_texture3path(std::string* texture3path) {
  if (texture3path != nullptr) {
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  texture3path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), texture3path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BBSerializer.BBMaterial.texture3Path)
}

// string texture4Path = 8;
inline bool BBMaterial::_internal_has_texture4path() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool BBMaterial::has_texture4path() const {
  return _internal_has_texture4path();
}
inline void BBMaterial::clear_texture4path() {
  texture4path_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000080u;
}
inline const std::string& BBMaterial::texture4path() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBMaterial.texture4Path)
  return _internal_texture4path();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void BBMaterial::set_texture4path(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000080u;
 texture4path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:BBSerializer.BBMaterial.texture4Path)
}
inline std::string* BBMaterial::mutable_texture4path() {
  // @@protoc_insertion_point(field_mutable:BBSerializer.BBMaterial.texture4Path)
  return _internal_mutable_texture4path();
}
inline const std::string& BBMaterial::_internal_texture4path() const {
  return texture4path_.Get();
}
inline void BBMaterial::_internal_set_texture4path(const std::string& value) {
  _has_bits_[0] |= 0x00000080u;
  texture4path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* BBMaterial::_internal_mutable_texture4path() {
  _has_bits_[0] |= 0x00000080u;
  return texture4path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BBMaterial::release_texture4path() {
  // @@protoc_insertion_point(field_release:BBSerializer.BBMaterial.texture4Path)
  if (!_internal_has_texture4path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000080u;
  return texture4path_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BBMaterial::set_allocated_texture4path(std::string* texture4path) {
  if (texture4path != nullptr) {
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  texture4path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), texture4path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BBSerializer.BBMaterial.texture4Path)
}

// string texture5Path = 9;
inline bool BBMaterial::_internal_has_texture5path() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool BBMaterial::has_texture5path() const {
  return _internal_has_texture5path();
}
inline void BBMaterial::clear_texture5path() {
  texture5path_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000100u;
}
inline const std::string& BBMaterial::texture5path() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBMaterial.texture5Path)
  return _internal_texture5path();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void BBMaterial::set_texture5path(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000100u;
 texture5path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:BBSerializer.BBMaterial.texture5Path)
}
inline std::string* BBMaterial::mutable_texture5path() {
  // @@protoc_insertion_point(field_mutable:BBSerializer.BBMaterial.texture5Path)
  return _internal_mutable_texture5path();
}
inline const std::string& BBMaterial::_internal_texture5path() const {
  return texture5path_.Get();
}
inline void BBMaterial::_internal_set_texture5path(const std::string& value) {
  _has_bits_[0] |= 0x00000100u;
  texture5path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* BBMaterial::_internal_mutable_texture5path() {
  _has_bits_[0] |= 0x00000100u;
  return texture5path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BBMaterial::release_texture5path() {
  // @@protoc_insertion_point(field_release:BBSerializer.BBMaterial.texture5Path)
  if (!_internal_has_texture5path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000100u;
  return texture5path_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BBMaterial::set_allocated_texture5path(std::string* texture5path) {
  if (texture5path != nullptr) {
    _has_bits_[0] |= 0x00000100u;
  } else {
    _has_bits_[0] &= ~0x00000100u;
  }
  texture5path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), texture5path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BBSerializer.BBMaterial.texture5Path)
}

// string texture6Path = 10;
inline bool BBMaterial::_internal_has_texture6path() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool BBMaterial::has_texture6path() const {
  return _internal_has_texture6path();
}
inline void BBMaterial::clear_texture6path() {
  texture6path_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000200u;
}
inline const std::string& BBMaterial::texture6path() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBMaterial.texture6Path)
  return _internal_texture6path();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void BBMaterial::set_texture6path(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000200u;
 texture6path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:BBSerializer.BBMaterial.texture6Path)
}
inline std::string* BBMaterial::mutable_texture6path() {
  // @@protoc_insertion_point(field_mutable:BBSerializer.BBMaterial.texture6Path)
  return _internal_mutable_texture6path();
}
inline const std::string& BBMaterial::_internal_texture6path() const {
  return texture6path_.Get();
}
inline void BBMaterial::_internal_set_texture6path(const std::string& value) {
  _has_bits_[0] |= 0x00000200u;
  texture6path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* BBMaterial::_internal_mutable_texture6path() {
  _has_bits_[0] |= 0x00000200u;
  return texture6path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BBMaterial::release_texture6path() {
  // @@protoc_insertion_point(field_release:BBSerializer.BBMaterial.texture6Path)
  if (!_internal_has_texture6path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000200u;
  return texture6path_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BBMaterial::set_allocated_texture6path(std::string* texture6path) {
  if (texture6path != nullptr) {
    _has_bits_[0] |= 0x00000200u;
  } else {
    _has_bits_[0] &= ~0x00000200u;
  }
  texture6path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), texture6path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BBSerializer.BBMaterial.texture6Path)
}

// string texture7Path = 11;
inline bool BBMaterial::_internal_has_texture7path() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool BBMaterial::has_texture7path() const {
  return _internal_has_texture7path();
}
inline void BBMaterial::clear_texture7path() {
  texture7path_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000400u;
}
inline const std::string& BBMaterial::texture7path() const {
  // @@protoc_insertion_point(field_get:BBSerializer.BBMaterial.texture7Path)
  return _internal_texture7path();
}
template <typename ArgT0, typename... ArgT>
PROTOBUF_ALWAYS_INLINE
inline void BBMaterial::set_texture7path(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000400u;
 texture7path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArena());
  // @@protoc_insertion_point(field_set:BBSerializer.BBMaterial.texture7Path)
}
inline std::string* BBMaterial::mutable_texture7path() {
  // @@protoc_insertion_point(field_mutable:BBSerializer.BBMaterial.texture7Path)
  return _internal_mutable_texture7path();
}
inline const std::string& BBMaterial::_internal_texture7path() const {
  return texture7path_.Get();
}
inline void BBMaterial::_internal_set_texture7path(const std::string& value) {
  _has_bits_[0] |= 0x00000400u;
  texture7path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline std::string* BBMaterial::_internal_mutable_texture7path() {
  _has_bits_[0] |= 0x00000400u;
  return texture7path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BBMaterial::release_texture7path() {
  // @@protoc_insertion_point(field_release:BBSerializer.BBMaterial.texture7Path)
  if (!_internal_has_texture7path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000400u;
  return texture7path_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BBMaterial::set_allocated_texture7path(std::string* texture7path) {
  if (texture7path != nullptr) {
    _has_bits_[0] |= 0x00000400u;
  } else {
    _has_bits_[0] &= ~0x00000400u;
  }
  texture7path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), texture7path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:BBSerializer.BBMaterial.texture7Path)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace BBSerializer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_BBMaterial_2eproto
